const AREAS = {
  'seoul-station': {
    title: '서울역 주차장 비교',
    description: '서울역 주변 주차장의 예상요금, 운영시간, 주차면수를 한눈에 비교합니다.',
    intro: '서울역은 짧은 픽업부터 장시간 주차까지 이용 목적이 다양합니다. 아래 비교표는 예시 데이터로 화면 구조와 계산 기능을 먼저 검증하기 위한 프로토타입입니다.',
    tip: '실제 운영 버전에서는 공공데이터 기준일과 관리기관 정보를 함께 표시하고, 현장 안내가 공개 데이터보다 우선한다는 점을 명확히 안내합니다.',
    lots: [
      {name:'서울역 A 공영주차장',address:'서울 중구 예시로 1',spaces:120,basicMinutes:30,basicFee:1500,addMinutes:10,addFee:500,dailyFee:18000,hours:'06:00–24:00'},
      {name:'서울역 B 주차장',address:'서울 중구 예시로 2',spaces:80,basicMinutes:30,basicFee:2000,addMinutes:10,addFee:400,dailyFee:16000,hours:'24시간'},
      {name:'서울역 C 주차장',address:'서울 용산구 예시로 3',spaces:65,basicMinutes:60,basicFee:3000,addMinutes:10,addFee:500,dailyFee:20000,hours:'24시간'}
    ]
  },
  'jongno': {
    title: '종로 주차장 비교', description: '종로 주변 주차장의 예상요금과 운영시간을 비교합니다.',
    intro: '종로는 목적지에 따라 도보 이동 거리가 크게 달라질 수 있어 요금뿐 아니라 운영시간과 주차면수도 함께 확인하는 편이 좋습니다.',
    tip: '행사·공사·시설 사정에 따라 운영정보가 달라질 수 있으므로 실제 방문 전 관리기관 안내를 확인하세요.',
    lots:[
      {name:'종로 A 공영주차장',address:'서울 종로구 예시로 1',spaces:72,basicMinutes:30,basicFee:1000,addMinutes:10,addFee:500,dailyFee:15000,hours:'07:00–23:00'},
      {name:'종로 B 공영주차장',address:'서울 종로구 예시로 2',spaces:150,basicMinutes:30,basicFee:1500,addMinutes:10,addFee:500,dailyFee:18000,hours:'24시간'},
      {name:'종로 C 주차장',address:'서울 종로구 예시로 3',spaces:55,basicMinutes:60,basicFee:3000,addMinutes:10,addFee:600,dailyFee:20000,hours:'08:00–22:00'}
    ]
  },
  'jamsil': {
    title: '잠실 주차장 비교', description: '잠실 주변 주차장의 예상요금과 운영시간을 비교합니다.',
    intro: '잠실은 경기·공연 일정에 따라 혼잡도가 크게 달라질 수 있습니다. 이 페이지는 여러 후보를 같은 기준으로 비교하는 화면 예시입니다.',
    tip: '실시간 만차 여부는 별도 데이터가 필요합니다. 운영 버전에서는 제공 가능한 정보와 제공하지 못하는 정보를 구분해서 표시합니다.',
    lots:[
      {name:'잠실 A 주차장',address:'서울 송파구 예시로 1',spaces:220,basicMinutes:30,basicFee:1200,addMinutes:10,addFee:400,dailyFee:17000,hours:'24시간'},
      {name:'잠실 B 공영주차장',address:'서울 송파구 예시로 2',spaces:95,basicMinutes:60,basicFee:2500,addMinutes:10,addFee:500,dailyFee:16000,hours:'06:00–24:00'},
      {name:'잠실 C 주차장',address:'서울 송파구 예시로 3',spaces:140,basicMinutes:30,basicFee:1800,addMinutes:10,addFee:500,dailyFee:19000,hours:'24시간'}
    ]
  },
  'kintex': {
    title: '킨텍스 주차장 비교', description: '킨텍스 주변 주차장의 예상요금과 운영시간을 비교합니다.',
    intro: '킨텍스처럼 행사 수요가 큰 장소는 짧은 시간보다 3시간·6시간·하루 기준 예상요금 비교가 더 유용할 수 있습니다.',
    tip: '실제 데이터 연결 시 행사장 자체 주차장과 주변 공영주차장을 구분하고, 각 데이터의 기준일을 표시합니다.',
    lots:[
      {name:'킨텍스 A 주차장',address:'경기 고양시 예시로 1',spaces:300,basicMinutes:30,basicFee:1000,addMinutes:10,addFee:300,dailyFee:12000,hours:'24시간'},
      {name:'킨텍스 B 공영주차장',address:'경기 고양시 예시로 2',spaces:180,basicMinutes:60,basicFee:2000,addMinutes:10,addFee:400,dailyFee:10000,hours:'06:00–24:00'},
      {name:'킨텍스 C 주차장',address:'경기 고양시 예시로 3',spaces:110,basicMinutes:30,basicFee:1500,addMinutes:10,addFee:400,dailyFee:14000,hours:'24시간'}
    ]
  }
};

const CSS = `:root{--bg:#f6f7f9;--card:#fff;--text:#17202a;--muted:#667085;--line:#e4e7ec;--blue:#1769d2;--soft:#edf4ff;--max:1080px}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,"Segoe UI","Noto Sans KR",sans-serif;line-height:1.65}a{color:inherit;text-decoration:none}header{position:sticky;top:0;background:#fff;border-bottom:1px solid var(--line);z-index:10}.nav{max-width:var(--max);margin:auto;padding:14px 20px;display:flex;justify-content:space-between;align-items:center}.brand{font-weight:900;font-size:1.14rem}.brand b{color:var(--blue)}.links{display:flex;gap:16px;color:var(--muted);font-size:.92rem}main{max-width:var(--max);margin:auto;padding:34px 20px 70px}.hero{padding:50px 0 26px}.hero h1{font-size:clamp(2.1rem,6vw,3.9rem);line-height:1.1;letter-spacing:-.045em;margin:8px 0 16px}.hero p{max-width:720px;color:var(--muted);font-size:1.05rem}.pill{display:inline-block;background:var(--soft);color:var(--blue);padding:6px 10px;border-radius:999px;font-weight:800;font-size:.82rem}.search{display:flex;gap:8px;max-width:720px;margin-top:24px}.search input{flex:1;min-width:0;padding:15px 17px;border:1px solid var(--line);border-radius:13px;background:#fff;font-size:1rem}.btn{border:0;background:var(--blue);color:#fff;border-radius:12px;padding:13px 17px;font-weight:800;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:20px}.card h2,.card h3{margin-top:0}.muted{color:var(--muted)}.small{font-size:.88rem}.section{margin-top:34px}.area-link{display:block}.area-link:hover{border-color:#b9cdf0}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.duration{padding:10px 14px;border:1px solid var(--line);background:#fff;border-radius:10px;font-weight:800;cursor:pointer}.duration.active{background:var(--blue);color:#fff;border-color:var(--blue)}.table-wrap{overflow:auto;background:#fff;border:1px solid var(--line);border-radius:18px}table{width:100%;border-collapse:collapse;min-width:760px}th,td{padding:14px 15px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:.87rem;color:var(--muted);background:#fbfcfd}.fee{font-weight:900}.notice{background:#fff8e8;border:1px solid #f2dfad;padding:15px 17px;border-radius:14px}.article{max-width:780px;background:#fff;border:1px solid var(--line);border-radius:20px;padding:28px}.article h1{letter-spacing:-.035em}.article h2{margin-top:30px}.crumbs{font-size:.88rem;color:var(--muted);margin-bottom:12px}footer{border-top:1px solid var(--line);background:#fff}.foot{max-width:var(--max);margin:auto;padding:24px 20px;color:var(--muted);font-size:.88rem}.foot a{margin-right:14px}@media(max-width:720px){.links{display:none}.grid{grid-template-columns:1fr}.hero{padding-top:28px}.search{flex-direction:column}.btn{width:100%}.article{padding:20px}.card{padding:17px}}`;

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function origin(env){return (env.SITE_ORIGIN||'http://localhost:8787').replace(/\/$/,'');}
function fee(lot,minutes){let v=lot.basicFee;if(minutes>lot.basicMinutes)v+=Math.ceil((minutes-lot.basicMinutes)/lot.addMinutes)*lot.addFee;if(lot.dailyFee)v=Math.min(v,lot.dailyFee);return v;}
function layout(env,{title,description,body,path='/',noindex=false}){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(origin(env)+path)}">${noindex?'<meta name="robots" content="noindex,follow">':''}<style>${CSS}</style></head><body><header><div class="nav"><a class="brand" href="/"><b>주차</b>비교</a><nav class="links"><a href="/guide">비교 가이드</a><a href="/data-policy">데이터 정책</a><a href="/about">서비스 소개</a></nav></div></header><main>${body}</main><footer><div class="foot"><a href="/about">서비스 소개</a><a href="/data-policy">데이터 정책</a><a href="/privacy">개인정보처리방침</a><a href="/contact">문의</a><p>© 2026 주차비교. 실제 요금·운영정보는 현장 안내가 우선합니다.</p></div></footer><script>document.addEventListener('click',e=>{const b=e.target.closest('[data-min]');if(!b)return;document.querySelectorAll('[data-min]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const m=+b.dataset.min;document.querySelectorAll('[data-fee]').forEach(x=>{const f=+x.dataset.bf+(m>+x.dataset.bm?Math.ceil((m-+x.dataset.bm)/+x.dataset.am)*+x.dataset.af:0);const v=+x.dataset.daily?Math.min(f,+x.dataset.daily):f;x.textContent=v.toLocaleString('ko-KR')+'원'})});</script></body></html>`;}
function home(env){const cards=Object.entries(AREAS).map(([slug,a])=>`<a class="card area-link" href="/parking/${slug}"><span class="pill">장소별 비교</span><h2>${esc(a.title)}</h2><p class="muted">${esc(a.description)}</p></a>`).join('');const body=`<section class="hero"><span class="pill">주차시간별 예상요금 비교</span><h1>주차장,<br>가격부터 비교하세요.</h1><p>가까운 곳만 찾는 대신 1시간·3시간·6시간 기준 예상요금과 운영시간을 같은 화면에서 비교하는 정보 서비스입니다.</p><form class="search" action="/search"><input name="q" placeholder="예: 서울역, 종로, 잠실"><button class="btn">검색</button></form></section><section class="section"><h2>먼저 비교해볼 장소</h2><div class="grid">${cards}</div></section><section class="section grid"><div class="card"><h3>단순 목록이 아닙니다</h3><p class="muted">기본요금과 추가요금을 이용해 시간별 예상금액을 계산하고 후보를 같은 기준으로 비교합니다.</p></div><div class="card"><h3>데이터 기준을 공개합니다</h3><p class="muted">운영 버전에서는 공공데이터 출처, 기준일, 계산 한계를 페이지에 표시합니다.</p></div></section>`;return layout(env,{title:'주차비교 | 장소별 주차장 예상요금 비교',description:'서울역·종로·잠실·킨텍스 등 주요 장소 주변 주차장의 예상요금과 운영시간을 비교합니다.',body});}
function area(env,slug){const a=AREAS[slug];if(!a)return null;const rows=a.lots.map(l=>`<tr><td><strong>${esc(l.name)}</strong><div class="small muted">${esc(l.address)}</div></td><td>${l.spaces.toLocaleString()}면</td><td>${esc(l.hours)}</td><td class="fee" data-fee data-bm="${l.basicMinutes}" data-bf="${l.basicFee}" data-am="${l.addMinutes}" data-af="${l.addFee}" data-daily="${l.dailyFee}">${fee(l,60).toLocaleString()}원</td><td>${l.dailyFee.toLocaleString()}원</td></tr>`).join('');const body=`<div class="crumbs"><a href="/">홈</a> › ${esc(a.title)}</div><section class="hero"><span class="pill">비교 페이지</span><h1>${esc(a.title)}</h1><p>${esc(a.intro)}</p></section><div class="notice"><strong>프로토타입 안내</strong><br>현재 표의 주차장명·주소·요금은 UI 검증용 예시입니다. 애드센스 신청 전 공식 공공데이터로 교체합니다.</div><div class="toolbar"><button class="duration active" data-min="60">1시간</button><button class="duration" data-min="180">3시간</button><button class="duration" data-min="360">6시간</button></div><div class="table-wrap"><table><thead><tr><th>주차장</th><th>주차면</th><th>운영시간</th><th>예상요금</th><th>1일권</th></tr></thead><tbody>${rows}</tbody></table></div><section class="section grid"><div class="card"><h3>이용 전 확인</h3><p class="muted">${esc(a.tip)}</p></div><div class="card"><h3>예상요금 계산 기준</h3><p class="muted">기본시간·기본요금·추가단위요금으로 단순 계산하며 일일권이 더 저렴하면 일일권 금액을 상한으로 사용합니다.</p></div></section>`;return layout(env,{title:`${a.title} | 주차비교`,description:a.description,body,path:`/parking/${slug}`});}
function article(env,title,description,html,path){return layout(env,{title:`${title} | 주차비교`,description,body:`<article class="article"><div class="crumbs"><a href="/">홈</a> › ${esc(title)}</div><h1>${esc(title)}</h1>${html}</article>`,path});}
function search(env,url){const q=(url.searchParams.get('q')||'').trim().toLowerCase();const hits=Object.entries(AREAS).filter(([slug,a])=>(slug+' '+a.title).toLowerCase().includes(q));const list=hits.length?hits.map(([slug,a])=>`<a class="card area-link" href="/parking/${slug}"><h2>${esc(a.title)}</h2><p class="muted">${esc(a.description)}</p></a>`).join(''):'<div class="card"><p>일치하는 장소가 없습니다.</p></div>';return layout(env,{title:`${q||'주차장'} 검색 | 주차비교`,description:'주차장 비교 검색 결과입니다.',body:`<section class="hero"><h1>검색 결과</h1><p>“${esc(q)}”에 대한 결과입니다.</p></section><div class="grid">${list}</div>`,path:'/search',noindex:true});}

export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/')return html(home(env));if(url.pathname==='/search')return html(search(env,url));if(url.pathname.startsWith('/parking/')){const page=area(env,url.pathname.split('/')[2]);return page?html(page):html(notFound(env),404)}if(url.pathname==='/guide')return html(article(env,'주차비 비교 가이드','주차장 요금을 비교할 때 확인할 기준을 설명합니다.','<p>주차장은 가까운 거리만으로 고르기보다 <strong>예상 이용시간, 기본요금, 추가요금, 일일권, 운영시간</strong>을 함께 보는 편이 좋습니다.</p><h2>1. 예상 이용시간부터 정하기</h2><p>30분 방문과 6시간 주차는 가장 저렴한 주차장이 달라질 수 있습니다.</p><h2>2. 운영시간 확인하기</h2><p>저렴해도 출차 가능 시간이 맞지 않으면 이용하기 어렵습니다.</p><h2>3. 데이터 기준일 확인하기</h2><p>공개 데이터는 현장 변경사항과 시차가 생길 수 있으므로 최종적으로는 현장 안내를 확인해야 합니다.</p>','/guide'));if(url.pathname==='/data-policy')return html(article(env,'데이터 정책','주차비교의 데이터 출처와 갱신 원칙을 안내합니다.','<p>운영 버전은 공공데이터포털의 전국주차장정보표준데이터 등 신뢰할 수 있는 공개 데이터를 사용합니다.</p><h2>가공 원칙</h2><p>원본 목록을 그대로 복제하지 않고 시간별 예상요금 계산, 같은 장소 후보 비교, 기준일 표시를 추가합니다.</p><h2>오류와 시차</h2><p>공개 데이터가 현장보다 늦게 갱신될 수 있습니다. 실제 요금과 운영정보는 현장 안내가 우선합니다.</p>','/data-policy'));if(url.pathname==='/about')return html(article(env,'서비스 소개','주차비교 서비스의 목적을 소개합니다.','<p>주차비교는 목적지 주변 주차장을 같은 기준으로 비교해 사용자가 짧은 시간 안에 선택할 수 있도록 돕는 정보 서비스입니다.</p><p>광고를 위한 빈 페이지를 대량 생성하는 대신 비교할 정보가 충분하고 직접 검수한 장소 페이지부터 공개하는 것을 운영 원칙으로 합니다.</p>','/about'));if(url.pathname==='/privacy')return html(article(env,'개인정보처리방침','주차비교의 개인정보 처리 원칙입니다.',`<p>현재 프로토타입은 회원가입을 제공하지 않습니다.</p><h2>로그 정보</h2><p>서비스 안정성 확인을 위해 호스팅 사업자가 접속 시각, 브라우저 정보 등 기술적 로그를 처리할 수 있습니다.</p><h2>광고</h2><p>Google AdSense를 실제로 도입하는 시점에 광고 쿠키와 동의 절차를 운영 환경에 맞게 추가 검토합니다.</p><h2>문의</h2><p>${esc(env.CONTACT_EMAIL||'contact@example.com')}</p>`,'/privacy'));if(url.pathname==='/contact')return html(article(env,'문의','주차장 정보 수정과 서비스 문의 방법입니다.',`<p>운영 버전에서는 실제 정보 오류 제보를 받을 수 있도록 합니다.</p><p><strong>${esc(env.CONTACT_EMAIL||'contact@example.com')}</strong></p>`,'/contact'));if(url.pathname==='/robots.txt')return text(`User-agent: *\nAllow: /\nDisallow: /search\nSitemap: ${origin(env)}/sitemap.xml\n`);if(url.pathname==='/sitemap.xml'){const paths=['/','/guide','/data-policy','/about',...Object.keys(AREAS).map(x=>'/parking/'+x)];return xml(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${origin(env)+p}</loc></url>`).join('')}</urlset>`)}if(url.pathname==='/ads.txt')return text('# AdSense 승인 후 실제 publisher ID를 설정합니다.\n');return html(notFound(env),404)} };
function notFound(env){return layout(env,{title:'페이지를 찾을 수 없습니다 | 주차비교',description:'요청한 페이지를 찾을 수 없습니다.',body:'<article class="article"><h1>페이지를 찾을 수 없습니다</h1><p>메인에서 다시 검색해주세요.</p><p><a class="btn" href="/">메인으로</a></p></article>',path:'/404',noindex:true});}
function html(v,status=200){return new Response(v,{status,headers:{'content-type':'text/html; charset=utf-8'}})}
function text(v){return new Response(v,{headers:{'content-type':'text/plain; charset=utf-8'}})}
function xml(v){return new Response(v,{headers:{'content-type':'application/xml; charset=utf-8'}})}
